# Generated by Django 5.0.2 on 2024-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_oraders'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraders',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
