# Generated by Django 5.0.2 on 2024-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_oraders_address_alter_oraders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraders',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
