# Generated by Django 5.0.2 on 2024-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_oraders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
